#!/usr/bin/env python3
"""
train_forest.py — Train Random Forest on security event data and export as Rust constants.

Usage:
    python3 ml/train_forest.py [--input data.csv] [--output src/ml_trees.rs]

This generates const arrays that the Rust Random Forest uses — no runtime ML framework needed.
"""

import sys
import json
import numpy as np
from pathlib import Path

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import cross_val_score
except ImportError:
    print("Install scikit-learn: pip install scikit-learn")
    sys.exit(1)


FEATURES = [
    "wx_count",
    "mprotect_sum",
    "ptrace_sum",
    "syscall_rate",
    "blocked_ratio",
    "uid_is_root",
    "event_burst_ratio",
    "unique_event_diversity",
]

import pandas as pd

def load_training_data(csv_path="ml/dataset.csv"):
    if not Path(csv_path).exists():
        print(f"Error: Dataset {csv_path} not found.")
        print("Please run `python ml/generate_dataset.py` to create a sample dataset,")
        print("or collect real data using `ml/collect_training_data.py`.")
        sys.exit(1)
        
    df = pd.read_csv(csv_path)
    
    # Ensure all required features are present
    missing_features = [f for f in FEATURES if f not in df.columns]
    if missing_features:
        print(f"Error: Dataset is missing required features: {missing_features}")
        sys.exit(1)
        
    if 'label' not in df.columns:
        print("Error: Dataset must contain a 'label' column (0 for benign, 1 for malicious).")
        sys.exit(1)
        
    X = df[FEATURES].values
    y = df['label'].values
    
    return X, y


def tree_to_rust(tree, feature_names, node_id=0, depth=0):
    """Convert a sklearn decision tree to Rust TreeNode code."""
    left = tree.children_left[node_id]
    right = tree.children_right[node_id]

    indent = "    " * depth

    if left == -1:  # Leaf
        value = tree.value[node_id][0]
        prob = value[1] / value.sum() if value.sum() > 0 else 0.0
        return f"{indent}TreeNode::leaf({prob:.4})"

    feature = tree.feature[node_id]
    threshold = tree.threshold[node_id]

    left_code = tree_to_rust(tree, feature_names, left, depth + 1)
    right_code = tree_to_rust(tree, feature_names, right, depth + 1)

    return (
        f"{indent}TreeNode::split({feature}, {threshold:.4},\n"
        f"{left_code},\n"
        f"{right_code})"
    )


def main():
    print("Training Random Forest for Nexus Axiom ML...")

    X, y = load_training_data()
    print(f"   Training data: {len(X)} samples, {len(FEATURES)} features")

    clf = RandomForestClassifier(
        n_estimators=10,
        max_depth=8,
        random_state=42,
        min_samples_leaf=10,
    )
    clf.fit(X, y)

    scores = cross_val_score(clf, X, y, cv=5, scoring="f1")
    print(f"   Cross-validation F1: {scores.mean():.4f} ± {scores.std():.4f}")
    print(f"   Feature importances:")
    for name, imp in sorted(zip(FEATURES, clf.feature_importances_), key=lambda x: -x[1]):
        print(f"      {name}: {imp:.4f}")

    # Export as Rust code
    rust_code = "// Auto-generated by train_forest.py - do not edit manually\n\n"
    rust_code += "pub fn pretrained_trees() -> Vec<TreeNode> {\n    vec![\n"

    for i, estimator in enumerate(clf.estimators_):
        tree = estimator.tree_
        rust_code += f"        // Tree {i+1}\n"
        rust_code += tree_to_rust(tree, FEATURES, depth=2) + ",\n"

    rust_code += "    ]\n}\n"

    # Export as Rust code directly to ml_predictor.rs if it exists, otherwise to a standalone file
    target_rs = Path("src/ml_predictor.rs")
    if target_rs.exists():
        content = target_rs.read_text()
        # Find the pretrained function and replace its body
        start_marker = "fn pretrained() -> Self {"
        if start_marker in content:
            # Simple replacement strategy for the pretrained method
            parts = content.split(start_marker)
            # Find the closing brace of the pretrained method
            rest = parts[1]
            brace_count = 1
            idx = 0
            for i, char in enumerate(rest):
                if char == '{': brace_count += 1
                elif char == '}': brace_count -= 1
                if brace_count == 0:
                    idx = i
                    break
            
            new_method = f"{start_marker}\n        Self {{\n            trees: pretrained_trees(),\n        }}\n    }}\n\n{rust_code}"
            new_content = parts[0] + new_method + rest[idx+1:]
            
            # Write it back
            target_rs.write_text(new_content)
            print(f"\nSuccessfully injected {len(clf.estimators_)} trained trees into {target_rs}")
        else:
            print("Could not find `pub fn pretrained() -> Self` in ml_predictor.rs")
    else:
        output_path = Path("ml/exported_trees.rs")
        output_path.write_text(rust_code)
        print(f"\nExported {len(clf.estimators_)} trees to {output_path}")


if __name__ == "__main__":
    main()
