apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      hostPID: true
      hostNetwork: true
      tolerations:
        - operator: Exists
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: nexus-axiom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: bpf
              mountPath: /sys/fs/bpf
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: bpf
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
