/// ml_predictor.rs — Pure-Rust ML behavioral analysis with Random Forest.
///
/// Prediction pipeline: RandomForest → Heuristic fallback.
/// No external ML framework or Python dependency required for production.
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const SEQ_LEN: usize = 32;
const ANOMALY_Z_THRESHOLD: f32 = 2.5;

// ── Public types ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PredictionResult {
    pub confidence: f32,
    pub threat_level: ThreatLevel,
    pub attack_type: String,
    pub timestamp: f64,
    pub source: PredictionSource,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum ThreatLevel {
    Low,
    Medium,
    High,
    Critical,
}

impl ThreatLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
            Self::Critical => "CRITICAL",
        }
    }
    pub fn is_alert_worthy(&self) -> bool {
        matches!(self, Self::High | Self::Critical)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PredictionSource {
    RandomForest,
    Heuristic,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BehaviorEvent {
    pub event_type: u8,
    pub prot: u32,
    pub uid: u32,
    pub blocked: bool,
    pub syscall_rate: f32,
    pub mmap_count: u32,
    pub mprotect_count: u32,
    pub ptrace_count: u32,
}

// ── Feature vector for Random Forest ─────────────────────────────────────────

#[derive(Debug, Clone)]
struct FeatureVector {
    wx_count: f32,
    mprotect_sum: f32,
    ptrace_sum: f32,
    syscall_rate: f32,
    blocked_ratio: f32,
    uid_is_root: f32,
    event_burst_ratio: f32,
    unique_event_diversity: f32,
}

impl FeatureVector {
    fn as_array(&self) -> [f32; 8] {
        [
            self.wx_count,
            self.mprotect_sum,
            self.ptrace_sum,
            self.syscall_rate,
            self.blocked_ratio,
            self.uid_is_root,
            self.event_burst_ratio,
            self.unique_event_diversity,
        ]
    }
}

// ── Decision Tree Node ───────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct TreeNode {
    feature_idx: usize,
    threshold: f32,
    left: Option<Box<TreeNode>>,
    right: Option<Box<TreeNode>>,
    prediction: Option<f32>, // leaf value
}

impl TreeNode {
    fn leaf(value: f32) -> Self {
        Self {
            feature_idx: 0,
            threshold: 0.0,
            left: None,
            right: None,
            prediction: Some(value),
        }
    }

    fn split(feature: usize, thresh: f32, left: TreeNode, right: TreeNode) -> Self {
        Self {
            feature_idx: feature,
            threshold: thresh,
            left: Some(Box::new(left)),
            right: Some(Box::new(right)),
            prediction: None,
        }
    }

    fn predict(&self, features: &[f32; 8]) -> f32 {
        if let Some(p) = self.prediction {
            return p;
        }
        if features[self.feature_idx] <= self.threshold {
            self.left.as_ref().map_or(0.0, |n| n.predict(features))
        } else {
            self.right.as_ref().map_or(0.0, |n| n.predict(features))
        }
    }
}

// ── Random Forest ────────────────────────────────────────────────────────────

struct RandomForest {
    trees: Vec<TreeNode>,
}

impl RandomForest {
    /// Build pre-trained forest. Thresholds derived from security telemetry patterns.
    fn pretrained() -> Self {
        Self {
            trees: pretrained_trees(),
        }
    }

    // Auto-generated by train_forest.py - do not edit manually

    pub fn pretrained_trees() -> Vec<TreeNode> {
        vec![
            // Tree 1
            TreeNode::split(6, 1.75, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 2
            TreeNode::split(7, 0.45, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 3
            TreeNode::split(4, 0.0755, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 4
            TreeNode::split(
                2,
                0.5,
                TreeNode::split(4, 0.0765, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
                TreeNode::leaf(1.0),
            ),
            // Tree 5
            TreeNode::split(7, 0.45, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 6
            TreeNode::split(7, 0.45, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 7
            TreeNode::split(
                0,
                0.5,
                TreeNode::leaf(0.0),
                TreeNode::split(3, 44.48, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            ),
            // Tree 8
            TreeNode::split(3, 45.08, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 9
            TreeNode::split(4, 0.0755, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
            // Tree 10
            TreeNode::split(4, 0.075, TreeNode::leaf(0.0), TreeNode::leaf(1.0)),
        ]
    }

    fn predict(&self, features: &[f32; 8]) -> f32 {
        let sum: f32 = self.trees.iter().map(|t| t.predict(features)).sum();
        sum / self.trees.len() as f32
    }
}

// ── Per-PID state ────────────────────────────────────────────────────────────

#[derive(Debug)]
struct PidState {
    events: VecDeque<(Instant, BehaviorEvent)>,
    mmap_count: u32,
    mprotect_count: u32,
    ptrace_count: u32,
    event_count: u32,
    blocked_count: u32,
    window_start: Instant,
    recent_uid: u32,
    // Anomaly detection: running mean/variance
    rate_mean: f32,
    rate_m2: f32,
    rate_n: u32,
}

impl PidState {
    fn new() -> Self {
        Self {
            events: VecDeque::with_capacity(SEQ_LEN + 4),
            mmap_count: 0,
            mprotect_count: 0,
            ptrace_count: 0,
            event_count: 0,
            blocked_count: 0,
            window_start: Instant::now(),
            recent_uid: u32::MAX,
            rate_mean: 0.0,
            rate_m2: 0.0,
            rate_n: 0,
        }
    }

    fn add(&mut self, ev: BehaviorEvent) {
        let now = Instant::now();
        // Evict events older than 10s
        while self
            .events
            .front()
            .map_or(false, |(t, _)| now.duration_since(*t).as_secs() > 10)
        {
            self.events.pop_front();
        }
        self.mmap_count += ev.mmap_count;
        self.mprotect_count += ev.mprotect_count;
        self.ptrace_count += ev.ptrace_count;
        self.event_count += 1;
        if ev.blocked {
            self.blocked_count += 1;
        }
        self.recent_uid = ev.uid;

        // Welford's online algorithm for rate variance
        let rate = self.syscall_rate();
        self.rate_n += 1;
        let delta = rate - self.rate_mean;
        self.rate_mean += delta / self.rate_n as f32;
        let delta2 = rate - self.rate_mean;
        self.rate_m2 += delta * delta2;

        self.events.push_back((now, ev));
        if self.events.len() > SEQ_LEN + 4 {
            self.events.pop_front();
        }
    }

    fn syscall_rate(&self) -> f32 {
        let elapsed = self.window_start.elapsed().as_secs_f32().max(0.1);
        self.event_count as f32 / elapsed
    }

    fn rate_z_score(&self) -> f32 {
        if self.rate_n < 5 {
            return 0.0;
        }
        let variance = self.rate_m2 / self.rate_n as f32;
        let stddev = variance.sqrt().max(0.001);
        (self.syscall_rate() - self.rate_mean).abs() / stddev
    }

    fn extract_features(&self) -> FeatureVector {
        let wx = self
            .events
            .iter()
            .filter(|(_, e)| e.prot & 0x7 == 0x7)
            .count();
        let total = self.event_count.max(1) as f32;
        let blocked_ratio = self.blocked_count as f32 / total;
        let unique_types: std::collections::HashSet<u8> =
            self.events.iter().map(|(_, e)| e.event_type).collect();
        let diversity = unique_types.len() as f32 / 6.0; // 6 possible event types

        // Burst ratio: events in last 2s / events in last 10s
        let now = Instant::now();
        let recent_2s = self
            .events
            .iter()
            .filter(|(t, _)| now.duration_since(*t).as_secs() < 2)
            .count();
        let burst = if self.events.is_empty() {
            0.0
        } else {
            recent_2s as f32 / self.events.len() as f32 * 5.0
        };

        FeatureVector {
            wx_count: wx as f32,
            mprotect_sum: self.mprotect_count as f32,
            ptrace_sum: self.ptrace_count as f32,
            syscall_rate: self.syscall_rate(),
            blocked_ratio,
            uid_is_root: if self.recent_uid == 0 { 1.0 } else { 0.0 },
            event_burst_ratio: burst,
            unique_event_diversity: diversity,
        }
    }
}

// ── ML Predictor ─────────────────────────────────────────────────────────────

pub struct MlPredictor {
    pid_states: Arc<Mutex<HashMap<u32, PidState>>>,
    last_prediction: Arc<Mutex<HashMap<u32, (Instant, PredictionResult)>>>,
    prediction_interval: Duration,
    forest: RandomForest,
}

impl MlPredictor {
    pub fn new() -> Self {
        Self {
            pid_states: Arc::new(Mutex::new(HashMap::new())),
            last_prediction: Arc::new(Mutex::new(HashMap::new())),
            prediction_interval: Duration::from_millis(500),
            forest: RandomForest::pretrained(),
        }
    }

    pub fn record_and_predict(
        &self,
        pid: u32,
        uid: u32,
        event_type: u8,
        prot: u32,
        blocked: bool,
    ) -> Option<PredictionResult> {
        {
            let mut states = self.pid_states.lock().unwrap();
            let state = states.entry(pid).or_insert_with(PidState::new);
            state.add(BehaviorEvent {
                event_type,
                prot,
                uid,
                blocked,
                syscall_rate: state.syscall_rate(),
                mmap_count: if event_type == 1 { 1 } else { 0 },
                mprotect_count: if event_type == 4 { 1 } else { 0 },
                ptrace_count: if event_type == 5 { 1 } else { 0 },
            });
        }

        // Rate-limit predictions
        {
            let cache = self.last_prediction.lock().unwrap();
            if let Some((last_t, _)) = cache.get(&pid) {
                if last_t.elapsed() < self.prediction_interval {
                    return None;
                }
            }
        }

        let result = self.predict(pid);
        {
            let mut cache = self.last_prediction.lock().unwrap();
            cache.insert(pid, (Instant::now(), result.clone()));
        }
        Some(result)
    }

    pub fn last_prediction(&self, pid: u32) -> Option<PredictionResult> {
        self.last_prediction
            .lock()
            .unwrap()
            .get(&pid)
            .map(|(_, r)| r.clone())
    }

    pub fn remove_pid(&self, pid: u32) {
        self.pid_states.lock().unwrap().remove(&pid);
        self.last_prediction.lock().unwrap().remove(&pid);
    }

    fn predict(&self, pid: u32) -> PredictionResult {
        let (features, z_score) = {
            let states = self.pid_states.lock().unwrap();
            match states.get(&pid) {
                Some(s) => (s.extract_features(), s.rate_z_score()),
                None => return self.benign_result(),
            }
        };

        let now_ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs_f64();
        let feature_array = features.as_array();

        // Random Forest prediction
        let rf_score = self.forest.predict(&feature_array);

        // Anomaly boost: if z-score is high, boost confidence
        let anomaly_boost = if z_score > ANOMALY_Z_THRESHOLD {
            (z_score - ANOMALY_Z_THRESHOLD) * 0.05
        } else {
            0.0
        };
        let confidence = (rf_score + anomaly_boost).clamp(0.0, 1.0);

        let (threat_level, attack_type) = if confidence >= 0.85 {
            (ThreatLevel::Critical, classify_attack(&features))
        } else if confidence >= 0.65 {
            (ThreatLevel::High, classify_attack(&features))
        } else if confidence >= 0.40 {
            (ThreatLevel::Medium, "Suspicious Activity".into())
        } else {
            (ThreatLevel::Low, "Benign".into())
        };

        PredictionResult {
            confidence,
            threat_level,
            attack_type,
            timestamp: now_ts,
            source: PredictionSource::RandomForest,
        }
    }

    fn benign_result(&self) -> PredictionResult {
        PredictionResult {
            confidence: 0.0,
            threat_level: ThreatLevel::Low,
            attack_type: "Benign".into(),
            timestamp: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs_f64(),
            source: PredictionSource::Heuristic,
        }
    }
}

fn classify_attack(f: &FeatureVector) -> String {
    if f.ptrace_sum > 0.0 {
        "Process Injection via ptrace".into()
    } else if f.wx_count > 0.0 && f.mprotect_sum > 2.0 {
        "Shellcode Injection (W^X + mprotect chain)".into()
    } else if f.mprotect_sum > 4.0 {
        "Memory Permission Escalation".into()
    } else if f.event_burst_ratio > 4.0 {
        "Syscall Flood / Fork Bomb".into()
    } else if f.uid_is_root > 0.0 && f.wx_count > 0.0 {
        "Root Privilege Exploitation".into()
    } else {
        "Exploit Attempt".into()
    }
}

impl Default for MlPredictor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_benign_prediction() {
        let p = MlPredictor::new();
        let r = p.record_and_predict(9999, 1000, 6, 0, false);
        assert!(r.is_some());
        let r = r.unwrap();
        assert!(r.confidence < 0.4);
    }

    #[test]
    fn test_attack_prediction() {
        let p = MlPredictor::new();
        // Simulate rapid W^X events
        for i in 0..15 {
            let _ = p.record_and_predict(1337, 0, 1, 7, true);
            if i < 14 {
                // Reset rate limiter by manipulating cache
                p.last_prediction.lock().unwrap().remove(&1337);
            }
        }
        let r = p.record_and_predict(1337, 0, 1, 7, true);
        // After many blocked W^X events, prediction should be elevated
        if let Some(r) = r {
            assert!(r.confidence > 0.3);
        }
    }

    #[test]
    fn test_random_forest_deterministic() {
        let forest = RandomForest::pretrained();
        let benign = [0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.5, 0.2];
        let attack = [5.0, 6.0, 2.0, 500.0, 0.8, 1.0, 4.0, 0.8];
        assert!(forest.predict(&benign) < 0.3);
        assert!(forest.predict(&attack) > 0.6);
    }

    #[test]
    fn test_rate_limiting() {
        let p = MlPredictor::new();
        let r1 = p.record_and_predict(42, 0, 1, 7, true);
        assert!(r1.is_some());
        let r2 = p.record_and_predict(42, 0, 1, 7, true);
        assert!(r2.is_none()); // rate limited
    }
}
